# Generated by Django 3.2 on 2022-01-21 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='color_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('DELIVERED', 'DELIVERED')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='range',
            field=models.CharField(choices=[('10000-50000', '10000-50000'), ('500000-100000', '500000-100000'), ('110000-200000', '110000-200000')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='color_name',
            field=models.CharField(max_length=255),
        ),
    ]
